### ISSUE TITLE
Add more info to the add data set fields for users

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/ckan#119]

**Comment by MeWu-IDM** [comment]
some issues and comments:

- enddate's helptext is Temporal range **start date**, e.g. 2018-12-31.

- under purpose: should we use "tracking" rather than the verb "tracks" seems there is no subject 
 
- under extent, the "Enables spatial search." sentence seems abrupt, better rephrase to "this field enables..." or maybe not necessary to mention it

- under Restricted, use of "checked", should use "check" to be consistent with other instructions (see the "extent mode" info

**Comment by MeWu-IDM** [comment]
verified
