### ISSUE TITLE
Polygon Geojson display error

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#16]
Repro
(1) Create a dataset with location =Asia:Taiwan
(2) enter Geojson is below

{ "type": "Polygon", "coordinates": [ [ [ 116.709999084472997, 20.697500228881836 ], [ 116.709999084472997, 26.385419845581282 ], [ 122.10847473144554, 26.385419845581282 ], [ 122.10847473144554, 20.697500228881836 ], [ 116.709999084472997, 20.697500228881836 ] ] ] }
it passed the validation and dataset can be created

(3) go to dataset and restrict the filter from the map it seems to work 
![image](https://user-images.githubusercontent.com/40474438/63065606-8a4d6300-bebb-11e9-9c6e-a73313b7856e.png)

(4) but when you click on the dataset,  you will see below error
**86894786_jquery.js:220 Uncaught Error: Invalid GeoJSON object.
    at Function.geometryToLayer (dataset_map.js:8)
    at e.addData (dataset_map.js:8)
    at e.initialize (dataset_map.js:8)
    at new e (dataset_map.js:6)
    at Object.o.geoJson (dataset_map.js:8)
    at Module._onReady (dataset_map.js:171)
    at HTMLDocument.proxy (86894786_jquery.js:22)
    at mightThrow (86894786_jquery.js:209)
    at process (86894786_jquery.js:211)**

 Similar error also occurs for MultiPoint
{ "type": "MultiPoint", "coordinates": [ [100.0, 0.0], [101.0, 1.0] ] }

examples from https://tools.ietf.org/html/rfc7946

**Comment by DLukacevic-IDM** [comment]
The error is caused by extra spaces in the GeoJson string. The fix here could be to make sure extra spaces are removed. This seems to lower the priority of the bug. If fixing it requires too much new code we should push it to Phase 2.  

 {                "type": "Polygon",                "coordinates": [                    [                        [100.0, 0.0],                        [101.0, 0.0],                        [101.0, 1.0],                        [100.0, 1.0],                        [100.0, 0.0]                    ]                ]            }

**Comment by MeWu-IDM** [comment]
Validate the two failed scenarios  now worked
