### ISSUE TITLE
ckanext.harvest is missing from spatial extension

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#24]
it looks like harvesters implementation in the spatial extension depends on ckanext.harvest module but it is not in our repo, also tests failed due to missing modules
I am not sure if this is okay it seems we don't use the functionality
https://docs.ckan.org/projects/ckanext-spatial/en/latest/harvesters.html

**Comment by DLukacevic-IDM** [comment]
Spatial Harvester plugin is optional. Per CKAN install instructions 
"To use the Spatial Harvesters, you will need to install and configure the harvester extension: ckanext-harvest."

At this point we are not using any of its features nor there is any code dependency.  
The only place where non-harvester code is importing an harvester object is in "ckanext\spatial\commands\validation.py" for a paster command for validating a metadata file meets a certain standards. We don't use that command at this point.

Based on above I think we should close this bugs since there is no impact.

**Comment by MeWu-IDM** [comment]
spatial tests removed from the suite
