### ISSUE TITLE
 world with "manually set extent" checked still shows default in create dataset scenario

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#55]
click dataset and enter "World" in the location
check the Extent Mode to manual
change extent to 
{ "type": "Polygon", "coordinates": [ [ [ 0, -90 ], [ 360, 90 ], [ 0, 90 ], [ 360, -90 ], [ 0, -90 ] ] ] }

after the creation it is still using default
{ "type": "Polygon", "coordinates": [ [ [ -180, -90 ], [ -180, 90 ], [ 180, 90 ], [ 180, -90 ], [ -180, -90 ] ] ] }

it seems update dataset will allow manually overwrite but not created
related to #34

**Comment by DLukacevic-IDM** [comment]
This issue is in the converter module and related to #63. 

Debugging shows that initial submission of the dataset form is a unicode string. Only after resource form is submitted spatial mode (data[('spatial_data,)]) value is a list.

Given that solution for #63 is not obvious, in the interest of time, I'm implementing a workaround to handle case when spatial_mode is converted into list.

**Comment by MeWu-IDM** [comment]
verified fixed
